
#!/bin/bash
echo test $DB_APP_USER
echo $DB_APP_PASSWORD
echo $POSTGRES_DB
echo $DB_APP_USER
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_APP_USER WITH PASSWORD '$DB_APP_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DB_APP_USER;
    GRANT ALL ON schema public TO $DB_APP_USER;
EOSQL