version: '3.8'
services:
  db:
    container_name: postgres_container
    build:
      context: src/deployment
      dockerfile: db.dockerfile
    restart: always
    environment:
      DB_APP_USER: ${DB_APP_USER}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_USER: ${DB_ADMIN_USER}
      PGDATA: /var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  nest:
    container_name: nest_container
    build:
      context: ./
      dockerfile: ./src/deployment/nest.dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
