import { Box, Grid, ListItem, Paper, Stack, Typography } from '@mui/material';
import HistoryOfGame from '../HistoryOfGame';
import { myRate, sortPeoplReating } from '../../tools/statisticFunctions';
import { users } from '../../data/data';
import { UserGetProfileResponseDTO } from '../../tools/api.autogenerated';
import { useContext } from 'react';
import { profileContext } from '../ProfilePage';

const HistoryTab = (props: { person?: UserGetProfileResponseDTO }) => {
  const { isLoading, profile } = useContext(profileContext);

  const user = props.person ? props.person : profile;

  return (
    <>
      <Grid container columns={9}>
        <Grid item xs={12} md={9} p={5} alignItems="center">
          <Paper
            variant="outlined"
            sx={{
              backgroundColor: 'rgba(255, 255, 255, 0.01)',
            }}
          >
            <Stack>
              <Typography
                variant="h6"
                fontWeight={300}
                textAlign={'center'}
                mt={2}
                mb={2}
              >
                History of games:
              </Typography>
              <Box
                // border="solid"
                maxHeight="30vh"
                width="100%"
                height="50%"
                sx={{
                  overflowY: 'auto',
                  m: 'auto',
                }}
              >
                {(
                  user?.gameHistory as {
                    player1: {
                      username: string;
                      score: number;
                      winner: boolean;
                    };
                    player2: {
                      username: string;
                      score: number;
                      winner: boolean;
                    };
                    status: 'finished' | 'canceled';
                  }[]
                ).map((game, idx) => {
                  const me =
                    game.player1.username === user?.username
                      ? game.player1
                      : game.player2;
                  const other =
                    game.player1.username !== user?.username
                      ? game.player1
                      : game.player2;
                  return (
                    <ListItem
                      style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                      }}
                      key={idx}
                    >
                      <div>{user?.username}</div>
                      <div>{me.score > 10 ? 10 : me.score}</div>
                      {game.status === 'finished' && me.winner && (
                        <div
                          style={{
                            border: '2px solid green',
                            color: 'green',
                            padding: 5,
                            borderRadius: 6,
                          }}
                        >
                          Won
                        </div>
                      )}
                      {game.status === 'finished' && !me.winner && (
                        <div
                          style={{
                            border: '2px solid red',
                            color: 'red',
                            padding: 5,
                            borderRadius: 6,
                          }}
                        >
                          Lost
                        </div>
                      )}
                      {game.status === 'canceled' && (
                        <div
                          style={{
                            border: '2px solid grey',
                            color: 'grey',
                            padding: 5,
                            borderRadius: 6,
                          }}
                        >
                          Canceled
                        </div>
                      )}
                      <div>{other.score > 10 ? 10 : other.score}</div>
                      <div>{other.username}</div>
                    </ListItem>
                  );
                })}
              </Box>
            </Stack>
          </Paper>
        </Grid>
      </Grid>
    </>
  );
};

export default HistoryTab;
