import {
  Avatar,
  Box,
  Stack,
  Typography,
  Grid,
  ButtonGroup,
  Button,
  Menu,
  MenuItem,
  IconButton,
  Divider,
  Chip,
} from '@mui/material';
import SportsCricketIcon from '@mui/icons-material/SportsCricket';
import CircleIcon from '@mui/icons-material/Circle';
import { Link, useNavigate } from 'react-router-dom';
import MenuIcon from '@mui/icons-material/Menu';
import { useState } from 'react';
import { myApi } from '../tools/apiHandler';
import { FriendData } from '../tools/api.autogenerated';
import { Game, match, matches } from './WatchTheGame';
import { user, users } from '../data/data';

const MatchToWatch = (props: { match: Game; isLast: boolean }) => {
  const navigate = useNavigate();
  const { match, isLast } = props;

  return (
    <>
      <Grid container columns={12} alignItems="center">
        <Grid item xs={1} textAlign="right" /*border="solid"*/ />
        <Grid
          item
          xs={1}
          display="flex"
          justifyContent="center"
          my={1}
          /*border="solid"*/
        >
          <Link
            to={'/app/users/' + match.player1.username}
            style={{ textDecoration: 'none', color: 'inherit' }}
          >
            <Avatar
              sx={{ width: 40, height: 40 }}
              src={match.player1.imageUrl}
            ></Avatar>
          </Link>
        </Grid>
        <Grid item xs={2} textAlign="left" /*border="solid"*/>
          <Link
            to={'/app/users/' + match.player1.username}
            style={{ textDecoration: 'none', color: 'inherit' }}
          >
            <Typography>{match.player1.username}</Typography>
          </Link>
        </Grid>
        <Grid item xs={4} textAlign="center" /*border="solid"*/>
          <Button
            variant="contained"
            size="medium"
            sx={{ whiteSpace: 'nowrap' }}
            onClick={() => {
              navigate(`/app/watch/${match.id}`);
            }}
          >
            WATCH THE GAME
          </Button>
        </Grid>

        <Grid item xs={2} textAlign="right" /*border="solid"*/>
          <Link
            to={'/app/users/' + match.player2.username}
            style={{ textDecoration: 'none', color: 'inherit' }}
          >
            <Typography>{match.player2.username}</Typography>
          </Link>
        </Grid>
        <Grid
          item
          xs={1}
          display="flex"
          justifyContent="center"
          my={1}
          /*border="solid"*/
        >
          <Link
            to={'/app/users/' + match.player2.username}
            style={{ textDecoration: 'none', color: 'inherit' }}
          >
            <Avatar
              sx={{ width: 40, height: 40 }}
              src={match.player2.imageUrl}
            ></Avatar>
          </Link>
        </Grid>
        <Grid item xs={1} textAlign="right" /*border="solid"*/ />
      </Grid>
      {!isLast && <Divider />}
    </>
  );
};

export default MatchToWatch;
