import { Box, Divider, Grid, Typography } from '@mui/material';
import { useEffect } from 'react';
import { users, user } from '../data/data';
import { UserGetProfileResponseDTO } from '../tools/api.autogenerated';
import { sortPeoplReating } from '../tools/statisticFunctions';
import HistoryOfGame from './HistoryOfGame';
import AchievementsTab from './tabs/AchievementsTab';
import HistoryTab from './tabs/HistoryTab';

const findRate = (person: user) => {
  const theSortedPeople = sortPeoplReating([...users]);

  const index = theSortedPeople.findIndex(
    (element) => element.username === person.username,
  );
  return index + 1;
};

const PublicProfileInfo = (props: { user: UserGetProfileResponseDTO }) => {
  const { user } = props;

  useEffect(() => {
  }, [user]);
  if (user)
    return (
      <>
        <Grid item xs={10} sm={5} justifyContent="center">
          <Box sx={{ width: '100%', mt: '150px' }} textAlign="center">
            <Typography>PROFILE INFO</Typography>
            <Divider sx={{ width: '80%', m: 'auto', my: '20px' }} />
            <Grid container columns={8} my="30px">
              <Grid item xs={1} />
              <Grid item xs={3} textAlign="left">
                <Typography fontSize={20}>username: </Typography>
              </Grid>
              <Grid item xs={2} textAlign="left">
                <Typography fontSize={20}>{user.username}</Typography>
              </Grid>
            </Grid>
            <Grid container columns={8} my="30px">
              <Grid item xs={1} />
              <Grid item xs={3} textAlign="left">
                <Typography fontSize={20}>games: </Typography>
                <Typography fontSize={20}>
                  {(user.stats as any).played}
                </Typography>
              </Grid>
              <Grid item xs={2} textAlign="left">
                <Typography fontSize={20}>wins: </Typography>
                <Typography fontSize={20}>
                  {(user.stats as any).wins}
                </Typography>
              </Grid>
              <Grid item xs={2} textAlign="left">
                <Typography fontSize={20}>loses: </Typography>
                <Typography fontSize={20}>
                  {(user.stats as any).loses}
                </Typography>
              </Grid>
            </Grid>
            <Grid container columns={8} my="30px">
              <Grid item xs={1} />
              <Grid item xs={2} textAlign="left">
                <Typography fontSize={20}>Ladder level: </Typography>
                <Typography fontSize={20}>{(user as any).rank}</Typography>
              </Grid>
            </Grid>

            <Typography>{user.username} achievenemts:</Typography>
            <Grid container columns={8}>
              <Divider sx={{ width: '80%', m: 'auto', my: '20px' }} />
              <AchievementsTab person={user} />
            </Grid>

            <Grid container columns={8}>
              <HistoryTab person={user} />
            </Grid>
          </Box>
        </Grid>
      </>
    );
  else return <></>;
};

export default PublicProfileInfo;
