import { Container, Grid, Paper } from '@mui/material';
import PhotoProfile from './PhotoProfile';
import { users } from '../data/data';
import { useLocation, useParams } from 'react-router-dom';
import PublicProfileInfo from './PublicProfileInfo';
import { useQuery } from 'react-query';
import { myApi } from '../tools/apiHandler';
import { useEffect, useState } from 'react';
import { UserGetProfileResponseDTO } from '../tools/api.autogenerated';

const PublicProfilPage = (props: any) => {
  const { mode } = props;
  const params = useParams();
  const [user, setUser] = useState<UserGetProfileResponseDTO | null>(null);
  const { data, refetch } = useQuery(
    'user',
    () =>
      myApi.usersControllerGetOtherProfile(params.username!, {
        toastError: true,
      } as any),
    { enabled: params.username !== undefined },
  );

  useEffect(() => {
    if (!data) return;
    setUser(data?.data);
  }, [data]);

  useEffect(() => {
    refetch();
  }, [params.username]);
  return (
    <>
      <Container>
        <Paper
          elevation={1}
          sx={{
            minHeight: { xs: '40vh', md: '90vh' },
            borderRadius: '16px',
          }}
        >
          {user && (
            <Grid container columns={10} mt={10}>
              <PhotoProfile person={user} mode={mode} refetch={refetch} />
              <Grid item xs={0} md={1} />
              <PublicProfileInfo user={user} />
            </Grid>
          )}
        </Paper>
      </Container>
    </>
  );
};

export default PublicProfilPage;
