import { Button, useTheme } from '@mui/material';
import { FC, useCallback } from 'react';
import { NotificationDTO } from '../../tools/api.autogenerated';
import { myApi } from '../../tools/apiHandler';
import { NotificationMenuItem } from './NotificationMenuItem';

type FriendRequestAcceptedMenuItemProps = {
  notif: NotificationDTO;
  onRead?: (id: number) => void;
};


const FriendRequestAcceptedMenuItem: FC<FriendRequestAcceptedMenuItemProps> = (
  props,
  ) => {
  const theTheme = useTheme();
  return (
    <NotificationMenuItem
      date={props.notif.date}
      id={props.notif.id}
      title={'New friend'}
      isRead={props.notif.isRead}
    >
      <div className="notif-body"
          style={{ backgroundColor: theTheme.palette.background.paper }}
        >
        <span className="notif-username">
          {props.notif.content.friend.username}
        </span>{' '}
        accepted your friend request !
      </div>
    </NotificationMenuItem>
  );
};

export default FriendRequestAcceptedMenuItem;
